name: CI/CD

on:
    push:
      branches:
        - dev
    pull_request:
      branches:
        - dev
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

    #   - name: Run tests
    #     run: |
    #       . venv/bin/activate
    #       pytest

      - name: Build Docker image
        run: |
          docker build -t manishsoni123/updated_image:latest .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: manishsoni123
          password: Manish@123

      - name: Push Docker image to DockerHub
        run: |
          docker push manishsoni123/updated_image:latest

  